[package]
name = "mpt"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
eyre = "0.6"
hex = "0.4"
dotenvy = "0.15"
url = "2.5.0"
bytes = "1.5"
alloy = "1.0.6"
alloy-trie = { version = "0.8.1", features = ["ethereum"] }
